# Generated by Django 3.0.8 on 2020-08-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_todolist_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='short_note',
        ),
        migrations.AddField(
            model_name='todolist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
