# Generated by Django 3.0.8 on 2020-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_todolist_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='full_note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
